export const CHANGE_SEARCH_FIELD = "CHANGE_SEARCH_FIELD"

export const REQUEST_ROBOTS_PENDING = "REQUEST_ROBOTS_PENDING";
export const REQUEST_ROBOTS_SUCCESS = "REQUEST_ROBOTS_SUCCESS";
export const REQUEST_ROBOTS_FAILED = "REQUEST_ROBOTS_FAILED";

export const SET_COUNT = "SET_COUNT"
export const RESET_COUNT = "RESET_COUNT"

export const CLICK_CARD= "CLICK_CARD"
export const UNCLICK_CARD= "UNCLICK_CARD"